// <auto-generated />
using System;
using ApplicationFrontEnd.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApplicationFrontEnd.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationFrontEndDBContext))]
    partial class ApplicationFrontEndDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ApplicationFrontEnd.Core.AvisCotisation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DateGeneration")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EstAutomatique")
                        .HasColumnType("bit");

                    b.Property<decimal>("MontantAPayer")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MotifsAjustement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.ToTable("AvisCotisations");
                });

            modelBuilder.Entity("ApplicationFrontEnd.Core.Contribuable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Adresse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotDePasse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NAS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contribuables");
                });

            modelBuilder.Entity("ApplicationFrontEnd.Core.Request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("AdressePostale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AgentAssignéId")
                        .HasColumnType("int");

                    b.Property<int>("AnneeFiscale")
                        .HasColumnType("int");

                    b.Property<decimal>("AutresRevenus")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Citoyennete")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ContribuableId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateAssignationAgent")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSubmitted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RaisonRevision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("RevenusEmploi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.Property<string>("Telephone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ContribuableId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("ApplicationFrontEnd.Core.RequestItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CheminFichier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateUpload")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<string>("TypeDocument")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.ToTable("RequestItems");
                });

            modelBuilder.Entity("ApplicationFrontEnd.Core.AvisCotisation", b =>
                {
                    b.HasOne("ApplicationFrontEnd.Core.Request", "Request")
                        .WithOne("AvisCotisation")
                        .HasForeignKey("ApplicationFrontEnd.Core.AvisCotisation", "RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("ApplicationFrontEnd.Core.Request", b =>
                {
                    b.HasOne("ApplicationFrontEnd.Core.Contribuable", "Contribuable")
                        .WithMany("Declarations")
                        .HasForeignKey("ContribuableId");

                    b.Navigation("Contribuable");
                });

            modelBuilder.Entity("ApplicationFrontEnd.Core.RequestItem", b =>
                {
                    b.HasOne("ApplicationFrontEnd.Core.Request", "Request")
                        .WithMany("RequestItems")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("ApplicationFrontEnd.Core.Contribuable", b =>
                {
                    b.Navigation("Declarations");
                });

            modelBuilder.Entity("ApplicationFrontEnd.Core.Request", b =>
                {
                    b.Navigation("AvisCotisation");

                    b.Navigation("RequestItems");
                });
#pragma warning restore 612, 618
        }
    }
}
